/* ============================================================
   data.js – Product catalogue (24 items, 5 categories)
   ============================================================ */

const PRODUCTS = [
  /* ====== ELECTRONICS ====== */
  {
    id: 1,
    category: 'electronics',
    brand: 'Apple',
    title: 'Apple iPhone 15 Pro – 256GB Natural Titanium',
    desc: 'The most powerful iPhone ever with the A17 Pro chip, titanium design, and a 48MP main camera system. Features Action Button and USB 3 connectivity.',
    price: 99999,
    oldPrice: 119999,
    rating: 4.7,
    reviewCount: 24871,
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: true,
    stock: 'in',
    delivery: 'Tomorrow',
    isNew: false,
  },
  {
    id: 2,
    category: 'electronics',
    brand: 'Samsung',
    title: 'Samsung Galaxy S24 Ultra 5G – 512GB Titanium Black',
    desc: 'Breakthrough AI-powered Galaxy experience. Features the best-in-class Galaxy AI, integrated S Pen, and a 200MP camera.',
    price: 89999,
    oldPrice: 134999,
    rating: 4.5,
    reviewCount: 18320,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: true,
    stock: 'in',
    delivery: 'Today',
    isNew: false,
  },
  {
    id: 3,
    category: 'electronics',
    brand: 'Sony',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    desc: 'Industry-leading noise cancellation with 30-hour battery life, multipoint connection and crystal-clear hands-free calling.',
    price: 24990,
    oldPrice: 34990,
    rating: 4.8,
    reviewCount: 42100,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Tomorrow',
    isNew: false,
  },
  {
    id: 4,
    category: 'electronics',
    brand: 'Apple',
    title: 'Apple MacBook Air M3 – 13 inch, 16GB RAM, 512GB SSD',
    desc: 'Supercharged by the M3 chip. Up to 18 hours of battery life, fanless design, and a stunning Liquid Retina display.',
    price: 114900,
    oldPrice: 134900,
    rating: 4.9,
    reviewCount: 9834,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80',
    badge: 'new',
    prime: true,
    stock: 'low',
    delivery: 'Tomorrow',
    isNew: true,
  },
  {
    id: 5,
    category: 'electronics',
    brand: 'LG',
    title: 'LG 55" UHD 4K Smart LED TV – WebOS 23',
    desc: 'Cinematic picture quality powered by α7 AI Processor Gen6. Dolby Vision IQ and Dolby Atmos for an immersive experience.',
    price: 42990,
    oldPrice: 69999,
    rating: 4.3,
    reviewCount: 7200,
    image: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: false,
    stock: 'in',
    delivery: 'In 3 days',
    isNew: false,
  },
  {
    id: 6,
    category: 'electronics',
    brand: 'boAt',
    title: 'boAt Airdopes 141 Bluetooth Truly Wireless Earbuds',
    desc: 'Up to 42 hours of total playback, ENx™ technology for clear calls, and IPX4 water resistance for everyday use.',
    price: 799,
    oldPrice: 2990,
    rating: 4.1,
    reviewCount: 186742,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: true,
    stock: 'in',
    delivery: 'Today',
    isNew: false,
  },

  /* ====== FASHION ====== */
  {
    id: 7,
    category: 'fashion',
    brand: 'Levi\'s',
    title: 'Levi\'s Men\'s 511 Slim Fit Stretch Jeans',
    desc: 'The 511™ is our slim fit jean from the hip to the ankle. Sits below waist, slim through thigh and leg with a stretch fabric for all-day comfort.',
    price: 1799,
    oldPrice: 2999,
    rating: 4.4,
    reviewCount: 22100,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Tomorrow',
    isNew: false,
  },
  {
    id: 8,
    category: 'fashion',
    brand: 'Nike',
    title: 'Nike Air Max 270 Running Shoes for Men',
    desc: 'Inspired by the Air Max 180 and Air Max 93, the Nike Air Max 270 delivers unrivalled comfort from heel to toe.',
    price: 8999,
    oldPrice: 12995,
    rating: 4.6,
    reviewCount: 14700,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Tomorrow',
    isNew: false,
  },
  {
    id: 9,
    category: 'fashion',
    brand: 'Allen Solly',
    title: 'Allen Solly Men\'s Slim Fit Cotton Formal Shirt',
    desc: 'Premium wrinkle-resistant cotton formal shirt. Perfect for office meetings and casual outings with a slim-fit silhouette.',
    price: 649,
    oldPrice: 1299,
    rating: 4.0,
    reviewCount: 5300,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: false,
    stock: 'in',
    delivery: 'In 2 days',
    isNew: false,
  },
  {
    id: 10,
    category: 'fashion',
    brand: 'Puma',
    title: 'Puma Women\'s Sports Leggings with Pockets',
    desc: 'Moisture-wicking fabric with 4-way stretch. High-waist design with side pockets, perfect for yoga, gym and running.',
    price: 849,
    oldPrice: 1999,
    rating: 4.2,
    reviewCount: 8900,
    image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Today',
    isNew: false,
  },
  {
    id: 11,
    category: 'fashion',
    brand: 'Ray-Ban',
    title: 'Ray-Ban Wayfarer Classic Sunglasses – UV400',
    desc: 'An American icon. Polished black frame with crystal green G-15 lenses providing 100% UV protection.',
    price: 6490,
    oldPrice: 8890,
    rating: 4.7,
    reviewCount: 3100,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'low',
    delivery: 'Tomorrow',
    isNew: false,
  },
  {
    id: 12,
    category: 'fashion',
    brand: 'Campus',
    title: 'Campus Men\'s Casual Running Shoes – Lightweight',
    desc: 'Ultra-lightweight running shoes with breathable mesh upper and EVA cushioned sole for all-day comfort.',
    price: 799,
    oldPrice: 1499,
    rating: 4.0,
    reviewCount: 43200,
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: true,
    stock: 'in',
    delivery: 'Today',
    isNew: false,
  },

  /* ====== HOME ====== */
  {
    id: 13,
    category: 'home',
    brand: 'Prestige',
    title: 'Prestige Iris 750W Mixer Grinder – 4 Jars',
    desc: '4 stainless steel jars including a chutney jar and liquidising jar. Multitasking Speed Control knob for all grinding needs.',
    price: 2399,
    oldPrice: 4499,
    rating: 4.3,
    reviewCount: 31400,
    image: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: true,
    stock: 'in',
    delivery: 'Tomorrow',
    isNew: false,
  },
  {
    id: 14,
    category: 'home',
    brand: 'Pigeon',
    title: 'Pigeon 12-Liter Air Fryer with Digital Display',
    desc: 'Large 12L capacity with 8 preset cooking functions. Up to 85% less oil consumption, rapid air circulation technology.',
    price: 4499,
    oldPrice: 8999,
    rating: 4.1,
    reviewCount: 12800,
    image: 'https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: true,
    stock: 'in',
    delivery: 'In 2 days',
    isNew: false,
  },
  {
    id: 15,
    category: 'home',
    brand: 'Milton',
    title: 'Milton Thermosteel Flip Lid Flask 1000ml',
    desc: 'Double wall stainless steel vacuum insulated flask. Keeps beverages hot for 24 hours and cold for 48 hours.',
    price: 449,
    oldPrice: 799,
    rating: 4.5,
    reviewCount: 87600,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Today',
    isNew: false,
  },
  {
    id: 16,
    category: 'home',
    brand: 'Bajaj',
    title: 'Bajaj 1200mm Ceiling Fan with 5-Star Rating',
    desc: 'Premium 5-star rated ceiling fan with aerodynamic blades, delivering maximum air delivery at minimum power consumption.',
    price: 2199,
    oldPrice: 3499,
    rating: 4.4,
    reviewCount: 9200,
    image: 'https://images.unsplash.com/photo-1618945537845-6677c7849cc7?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: false,
    stock: 'in',
    delivery: 'In 3 days',
    isNew: false,
  },
  {
    id: 17,
    category: 'home',
    brand: 'Solimo',
    title: 'Amazon Solimo 10-Piece Non-Stick Cookware Set',
    desc: 'Complete kitchen set with aluminum base. PFOA-free non-stick coating, heat-resistant handles, and induction-compatible base.',
    price: 1899,
    oldPrice: 3499,
    rating: 4.2,
    reviewCount: 21700,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: true,
    stock: 'low',
    delivery: 'Tomorrow',
    isNew: false,
  },
  {
    id: 18,
    category: 'home',
    brand: 'Godrej',
    title: 'Godrej Aer Matic Kit – Automatic Air Freshener Spray',
    desc: 'Smart fragrance delivery at set intervals. 270+ sprays per refill, motion sensors for on-demand freshness.',
    price: 299,
    oldPrice: 549,
    rating: 4.1,
    reviewCount: 44300,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Today',
    isNew: false,
  },

  /* ====== BOOKS ====== */
  {
    id: 19,
    category: 'books',
    brand: 'HarperCollins',
    title: 'Atomic Habits by James Clear – Paperback',
    desc: 'The #1 New York Times bestseller. An easy and proven way to build good habits and break bad ones. Transform your life with tiny changes.',
    price: 349,
    oldPrice: 499,
    rating: 4.9,
    reviewCount: 193000,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Today',
    isNew: false,
  },
  {
    id: 20,
    category: 'books',
    brand: 'Penguin',
    title: 'The Psychology of Money by Morgan Housel – Paperback',
    desc: 'Timeless lessons on wealth, greed, and happiness. Morgan Housel shares 19 short stories exploring the strange ways people think about money.',
    price: 299,
    oldPrice: 499,
    rating: 4.8,
    reviewCount: 87400,
    image: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Today',
    isNew: false,
  },
  {
    id: 21,
    category: 'books',
    brand: 'O\'Reilly',
    title: 'Python Data Science Handbook by Jake VanderPlas',
    desc: 'Essential tools for working with data in Python. Covers IPython, NumPy, Pandas, Matplotlib, Scikit-Learn and more.',
    price: 799,
    oldPrice: 1299,
    rating: 4.7,
    reviewCount: 12300,
    image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=500&auto=format&fit=crop&q=80',
    badge: 'new',
    prime: false,
    stock: 'in',
    delivery: 'Tomorrow',
    isNew: true,
  },

  /* ====== SPORTS ====== */
  {
    id: 22,
    category: 'sports',
    brand: 'Yonex',
    title: 'Yonex Muscle Power 29 Badminton Racket',
    desc: 'Extra slim shaft for fast and quick swing. Isometric frame for larger sweet spot. Perfect for intermediate players.',
    price: 699,
    oldPrice: 1099,
    rating: 4.3,
    reviewCount: 14200,
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500&auto=format&fit=crop&q=80',
    badge: null,
    prime: true,
    stock: 'in',
    delivery: 'Tomorrow',
    isNew: false,
  },
  {
    id: 23,
    category: 'sports',
    brand: 'Cosco',
    title: 'Cosco Torneo Football – Size 5',
    desc: 'Hand-stitched, 32-panel design with butyl bladder for superior air retention. Suitable for all weather conditions.',
    price: 449,
    oldPrice: 799,
    rating: 4.0,
    reviewCount: 8700,
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: false,
    stock: 'in',
    delivery: 'In 2 days',
    isNew: false,
  },
  {
    id: 24,
    category: 'sports',
    brand: 'Boldfit',
    title: 'Boldfit Pro Gym Gloves with Wrist Support',
    desc: 'Premium leather palm with gel padding for grip and protection. Adjustable wrist strap for extra support during heavy lifts.',
    price: 349,
    oldPrice: 999,
    rating: 4.2,
    reviewCount: 28900,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
    badge: 'deal',
    prime: true,
    stock: 'low',
    delivery: 'Today',
    isNew: false,
  },
];